//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manejaClientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int idcliente { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public bool genero { get; set; }
        public string email { get; set; }
        public string domicilio { get; set; }
        public string ciudad { get; set; }
        public Nullable<decimal> codigo_postal { get; set; }
        public byte estado { get; set; }
    
        public virtual estado estado1 { get; set; }
    }
}
